accounts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/$', 'accounts.views.register', name="register"),
    url(r'^login/$', 'accounts.views.login', name="login"),
    url(r'^logout/$', 'accounts.views.logout', name="logout"),
]

ectocode/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'home.views.home', name="home"),
    url(r'^(?P<user_id>\d+)/$', 'home.views.profile', name="profile"),
    url(r'^profile-settings/$', 'home.views.profile_settings', name="profile_settings"),
    url(r'^account-settings/$', 'home.views.account_settings', name="account_settings"),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

    {% block css %}{% endblock %}


  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">EctoCode</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">

          {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">

            <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-bell" aria-hidden="true"></span> Notifications</a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create <small>&#9660;</small></a>
              <ul class="dropdown-menu">
                <li><a href="#">Code Review</a></li>
                <li><a href="#">Forum Post</a></li>
                <li><a href="#">Beta Testing</a></li>
              </ul>
          </li>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.username }} <small>&#9660;</small></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'profile' request.user.id %}">Profile</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'profile_settings' %}">Profile Settings</a></li>
                <li><a href="{% url 'account_settings' %}">Account Settings</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Report a Problem</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              </ul>
          </li>


          </ul>
          {% endif %}


        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      {% for message in messages %}
      	<p{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} style="text-align: center">{{ message }}</p>
      {% endfor %}


      <div class="starter-template">
        <div class="container">
        {% block content %}{% endblock %}
      </div>
    </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  </body>
</html>